[project]
name = "gridone-storage"
version = "0.1.0"
description = "Storage repository engine for gridone applications."
readme = "README.md"
authors = []

requires-python = ">=3.13"
dependencies = []

[tool.uv]
workspaces=true


[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "storage"
module-root = "src"

[tool.pytest.ini_options]
pythonpath = ["src"]
