[project]
name = "gridone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomqtt>=2.4.0",
    "httpx>=0.28.1",
    "pydantic>=2.12.4",
    "pymodbus>=3.11.3",
    "python-jsonpath>=2.0.1",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.3",
    "ty>=0.0.1a25",
]

[tool.ruff]
indent-width = 4
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
   "D"
]
fixable = ["ALL"]


[tool.ruff.lint.per-file-ignores]
"**/test_*.py" = ["SLF001", "T201", "TID252", "FBT001", "S101", "ANN401"]
