[project]
name = "dto"
version = "0.1.0"
description = "Data Transfer Object package implementing mappings between domain models (core) and "
readme = "README.md"
authors = [
    { email = "lucas.david@a-grid.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gridone-devices-manager",
    "pydantic>=2.12.4",
]

[tool.uv]
workspaces=true

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["src"]
