[project]
name = "gridone-timeseries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = []
requires-python = ">=3.13"
dependencies = ["gridone-models", "asyncpg>=0.30.0"]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"


[tool.pytest.ini_options]
markers = [
    "integration: mark a test as an integration test",
]

[tool.uv.build-backend]
module-name = "timeseries"
module-root = "src"
