[project]
name = "gridone-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = []
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.123.8",
    "gridone-storage",
    "pydantic-settings>=2.12.0",
]

[tool.uv]
workspaces=true


[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "api"
module-root = "src"

[tool.ruff.lint]
ignore=["B008"]
