[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gridone-core",
    "gridone-storage",
    "python-dotenv>=1.2.1",
    "typer>=0.20.0",
]

[tool.uv]
workspaces=true
